const hallRouter = {
    path: '/hall',
    name: 'hall',
    redirect: '/hall/resource',
    component: () => import('/@/layout/routerView/parent.vue'),
    meta: {
        title: '供需大厅',
        isLink: '',
        isHide: false,
        isKeepAlive: false,
        isAffix: true,
        isIframe: false,
        roles: ['admin', 'common'],
        icon: '',
    },
    children: [
        {
            path: '/hall/resource',
            name: 'resource',
            component: () => import('/@/views/hall/resource/index.vue'),
            meta: {
                title: '数转资源',
                isLink: '',
                isHide: false,
                isKeepAlive: false,
                isAffix: true,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: '',
            },
        },
        {
            path: '/hall/resource/detail',
            name: 'resourceDetail',
            component: () => import('/@/views/hall/resource/detail.vue'),
            meta: {
                title: '数转资源',
                isLink: '',
                isHide: true,
                isKeepAlive: false,
                isAffix: true,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: '',
            },
        },
        {
            path: '/hall/demand',
            name: 'demand',
            component: () => import('/@/views/hall/demand/index.vue'),
            meta: {
                title: '需求市场',
                isLink: '',
                isHide: false,
                isKeepAlive: false,
                isAffix: true,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: '',
            },
        },
        {
            path: '/hall/demand/detail',
            name: 'demandDetail',
            component: () => import('/@/views/hall/demand/detail.vue'),
            meta: {
                title: '需求详情',
                isLink: '',
                isHide: true,
                isKeepAlive: false,
                isAffix: true,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: '',
            },
        },
        {
            path: '/hall/demand/requirements',
            name: 'requirements',
            component: () => import('/@/views/hall/requirements/index.vue'),
            meta: {
                title: '发布需求',
                isLink: '',
                isHide: true,
                isKeepAlive: false,
                isAffix: true,
                isIframe: false,
                roles: ['admin', 'common'],
                icon: '',
            },
        },
    ]
};

export default hallRouter;
