version: '3'
networks:
    my-network:
        driver: bridge
services:
    mysql:
        image: mysql
        container_name: mysql57
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: xty
            MYSQL_PASSWORD: 123456
        ports:
            - '3307:3306'
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - my-network
    app:
        image: agent
        build: .
        ports:
            - '7001:7001'
        networks:
            - my-network
        depends_on:
            - mysql
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3307
            - MYSQL_USER=xty
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=test
